version: "3.9"
services:
  app:
    build: .
    volumes:
      - ./front:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    command: bash -c "npm run dev"
    tty: true
    # networks:
    #   - frontend
  db:
   image: postgres:14.2
   volumes:
    - ./db:/var/lib/postgresql/data
   env_file:
    - ./back/firstapp/.env
   ports:
    - "5432:5432"
  #  networks:
  #   - backend
  middle:
    image: node:lts
    tty: true
    expose:
      - 3000
      - 9229
    ports:
      - 4000:4000 #8000がホストのポート番号3000がコンテナのポート番号 
      - 9229:9229
    volumes:
      - ./back:/usr/src/app
    working_dir: /usr/src/app
    # command: npm run start:debug
    # networks:
    #   - frontend
    #   - backend
  pgadmin4:
    image: dpage/pgadmin4
    ports:
        - 8888:80
    volumes:
        - ./pgadmin4_data:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: xxxxxxxxxx@gmail.com
        PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
# networks:
#   frontend:
#     driver: bridge
#     ipam:
#       driver: default
#   backend:
#     driver: bridge
#     ipam:
#       driver: default